const data = [
  {
    "id": 1,
    "firstName": "Franni",
    "lastName": "Snary",
    "dateOfBirth": "1927-07-21",
    "startDate": "2009-06-11",
    "street": "Quincy",
    "city": "Salinas",
    "state": "California",
    "zipCode": "93907",
    "department": "HumanResources"
  },
  {
    "id": 2,
    "firstName": "Stefania",
    "lastName": "Youson",
    "dateOfBirth": "1981-02-11",
    "startDate": "2021-10-20",
    "street": "Eagle Crest",
    "city": "Harrisburg",
    "state": "Pennsylvania",
    "zipCode": "17105",
    "department": "Marketing"
  },
  {
    "id": 3,
    "firstName": "Livy",
    "lastName": "Dainty",
    "dateOfBirth": "1935-11-02",
    "startDate": "2016-10-11",
    "street": "Darwin",
    "city": "Minneapolis",
    "state": "Minnesota",
    "zipCode": "55448",
    "department": "Sales"
  },
  {
    "id": 4,
    "firstName": "Brose",
    "lastName": "Morford",
    "dateOfBirth": "1989-05-18",
    "startDate": "2004-09-22",
    "street": "Nancy",
    "city": "Oakland",
    "state": "California",
    "zipCode": "94627",
    "department": "Legal"
  },
  {
    "id": 5,
    "firstName": "Marylin",
    "lastName": "Swinney",
    "dateOfBirth": "1980-05-28",
    "startDate": "2008-01-14",
    "street": "Emmet",
    "city": "Yonkers",
    "state": "New York",
    "zipCode": "10705",
    "department": "Sales"
  },
  {
    "id": 6,
    "firstName": "Hannie",
    "lastName": "Yare",
    "dateOfBirth": "1939-03-11",
    "startDate": "2005-08-17",
    "street": "Novick",
    "city": "New York City",
    "state": "New York",
    "zipCode": "10024",
    "department": "Engineering"
  },
  {
    "id": 7,
    "firstName": "Antonia",
    "lastName": "Darley",
    "dateOfBirth": "1949-09-10",
    "startDate": "2008-12-15",
    "street": "Mitchell",
    "city": "Fayetteville",
    "state": "North Carolina",
    "zipCode": "28305",
    "department": "Legal"
  },
  {
    "id": 8,
    "firstName": "Lodovico",
    "lastName": "Seman",
    "dateOfBirth": "1956-10-31",
    "startDate": "2018-09-07",
    "street": "Service",
    "city": "Virginia Beach",
    "state": "Virginia",
    "zipCode": "23454",
    "department": "HumanResources"
  },
  {
    "id": 9,
    "firstName": "Rochell",
    "lastName": "Casari",
    "dateOfBirth": "2000-05-27",
    "startDate": "2006-07-12",
    "street": "Laurel",
    "city": "Kansas City",
    "state": "Missouri",
    "zipCode": "64179",
    "department": "HumanResources"
  },
  {
    "id": 10,
    "firstName": "Van",
    "lastName": "Gaunter",
    "dateOfBirth": "1938-11-19",
    "startDate": "2010-03-28",
    "street": "Londonderry",
    "city": "Chicago",
    "state": "Illinois",
    "zipCode": "60646",
    "department": "Legal"
  },
  {
    "id": 11,
    "firstName": "Marylynne",
    "lastName": "Topp",
    "dateOfBirth": "1998-12-31",
    "startDate": "2009-11-13",
    "street": "Village",
    "city": "Sacramento",
    "state": "California",
    "zipCode": "94207",
    "department": "Engineering"
  },
  {
    "id": 12,
    "firstName": "Raphaela",
    "lastName": "Le Provost",
    "dateOfBirth": "1976-02-21",
    "startDate": "2000-07-29",
    "street": "Cardinal",
    "city": "Longview",
    "state": "Texas",
    "zipCode": "75605",
    "department": "HumanResources"
  },
  {
    "id": 13,
    "firstName": "Pancho",
    "lastName": "Early",
    "dateOfBirth": "2001-03-01",
    "startDate": "2020-01-19",
    "street": "Sauthoff",
    "city": "Richmond",
    "state": "Virginia",
    "zipCode": "23242",
    "department": "HumanResources"
  },
  {
    "id": 14,
    "firstName": "Darelle",
    "lastName": "Kilroy",
    "dateOfBirth": "1991-12-09",
    "startDate": "2019-11-13",
    "street": "Merrick",
    "city": "Norfolk",
    "state": "Virginia",
    "zipCode": "23504",
    "department": "Sales"
  },
  {
    "id": 15,
    "firstName": "Geralda",
    "lastName": "Brogden",
    "dateOfBirth": "1962-04-15",
    "startDate": "2006-04-26",
    "street": "Summerview",
    "city": "Saint Louis",
    "state": "Missouri",
    "zipCode": "63143",
    "department": "Sales"
  },
  {
    "id": 16,
    "firstName": "Celene",
    "lastName": "Recher",
    "dateOfBirth": "1942-10-07",
    "startDate": "2016-04-24",
    "street": "Arrowood",
    "city": "Kansas City",
    "state": "Missouri",
    "zipCode": "64144",
    "department": "Legal"
  },
  {
    "id": 17,
    "firstName": "Jourdain",
    "lastName": "Borsay",
    "dateOfBirth": "1933-05-13",
    "startDate": "2013-02-13",
    "street": "Killdeer",
    "city": "San Francisco",
    "state": "California",
    "zipCode": "94137",
    "department": "Sales"
  },
  {
    "id": 18,
    "firstName": "Jo-ann",
    "lastName": "Habard",
    "dateOfBirth": "1929-02-11",
    "startDate": "2011-12-27",
    "street": "Farmco",
    "city": "Tyler",
    "state": "Texas",
    "zipCode": "75710",
    "department": "Marketing"
  },
  {
    "id": 19,
    "firstName": "Corette",
    "lastName": "Ianne",
    "dateOfBirth": "1991-04-16",
    "startDate": "2013-11-19",
    "street": "Bunker Hill",
    "city": "Sparks",
    "state": "Nevada",
    "zipCode": "89436",
    "department": "Marketing"
  },
  {
    "id": 20,
    "firstName": "Arri",
    "lastName": "Ottosen",
    "dateOfBirth": "1935-11-20",
    "startDate": "2022-05-26",
    "street": "Hooker",
    "city": "Shreveport",
    "state": "Louisiana",
    "zipCode": "71161",
    "department": "HumanResources"
  },
  {
    "id": 21,
    "firstName": "Clemens",
    "lastName": "Hafford",
    "dateOfBirth": "1960-09-23",
    "startDate": "2000-10-26",
    "street": "Vernon",
    "city": "Greensboro",
    "state": "North Carolina",
    "zipCode": "27409",
    "department": "Marketing"
  },
  {
    "id": 22,
    "firstName": "Yvor",
    "lastName": "Kelcher",
    "dateOfBirth": "1950-03-13",
    "startDate": "2017-04-27",
    "street": "Pond",
    "city": "Honolulu",
    "state": "Hawaii",
    "zipCode": "96810",
    "department": "Marketing"
  },
  {
    "id": 23,
    "firstName": "Nelle",
    "lastName": "Ensor",
    "dateOfBirth": "1946-11-07",
    "startDate": "2007-09-20",
    "street": "Nancy",
    "city": "Knoxville",
    "state": "Tennessee",
    "zipCode": "37939",
    "department": "HumanResources"
  },
  {
    "id": 24,
    "firstName": "Davidson",
    "lastName": "Nucci",
    "dateOfBirth": "1971-08-25",
    "startDate": "2000-12-20",
    "street": "Grim",
    "city": "Hamilton",
    "state": "Ohio",
    "zipCode": "45020",
    "department": "Engineering"
  },
  {
    "id": 25,
    "firstName": "Kelby",
    "lastName": "Capini",
    "dateOfBirth": "1966-03-19",
    "startDate": "2012-06-17",
    "street": "Eagle Crest",
    "city": "Kansas City",
    "state": "Missouri",
    "zipCode": "64109",
    "department": "Marketing"
  },
  {
    "id": 26,
    "firstName": "Ardra",
    "lastName": "Locket",
    "dateOfBirth": "1937-05-19",
    "startDate": "2002-08-12",
    "street": "Golf View",
    "city": "Metairie",
    "state": "Louisiana",
    "zipCode": "70033",
    "department": "Engineering"
  },
  {
    "id": 27,
    "firstName": "Luisa",
    "lastName": "Rodman",
    "dateOfBirth": "1951-07-27",
    "startDate": "2001-05-19",
    "street": "Crownhardt",
    "city": "Knoxville",
    "state": "Tennessee",
    "zipCode": "37924",
    "department": "Sales"
  },
  {
    "id": 28,
    "firstName": "Esra",
    "lastName": "Isakson",
    "dateOfBirth": "1931-01-15",
    "startDate": "2014-08-11",
    "street": "Melrose",
    "city": "Miami",
    "state": "Florida",
    "zipCode": "33196",
    "department": "HumanResources"
  },
  {
    "id": 29,
    "firstName": "Jobie",
    "lastName": "Miller",
    "dateOfBirth": "1969-03-13",
    "startDate": "2009-06-08",
    "street": "Summer Ridge",
    "city": "Shawnee Mission",
    "state": "Kansas",
    "zipCode": "66220",
    "department": "Engineering"
  },
  {
    "id": 30,
    "firstName": "Maximilien",
    "lastName": "Youde",
    "dateOfBirth": "1939-10-02",
    "startDate": "2005-02-03",
    "street": "Tennyson",
    "city": "Chicago",
    "state": "Illinois",
    "zipCode": "60619",
    "department": "HumanResources"
  },
  {
    "id": 31,
    "firstName": "Haze",
    "lastName": "Mulcock",
    "dateOfBirth": "1962-03-07",
    "startDate": "2013-06-21",
    "street": "Ryan",
    "city": "Raleigh",
    "state": "North Carolina",
    "zipCode": "27621",
    "department": "HumanResources"
  },
  {
    "id": 32,
    "firstName": "Laurianne",
    "lastName": "Vidyapin",
    "dateOfBirth": "1955-03-30",
    "startDate": "2013-10-22",
    "street": "Dapin",
    "city": "Whittier",
    "state": "California",
    "zipCode": "90610",
    "department": "HumanResources"
  },
  {
    "id": 33,
    "firstName": "Aldric",
    "lastName": "Sessuns",
    "dateOfBirth": "1977-04-11",
    "startDate": "2010-12-29",
    "street": "Tony",
    "city": "Boise",
    "state": "Idaho",
    "zipCode": "83705",
    "department": "Legal"
  },
  {
    "id": 34,
    "firstName": "Carlyn",
    "lastName": "Ehrat",
    "dateOfBirth": "1988-09-15",
    "startDate": "2016-01-29",
    "street": "Marquette",
    "city": "Oklahoma City",
    "state": "Oklahoma",
    "zipCode": "73197",
    "department": "Marketing"
  },
  {
    "id": 35,
    "firstName": "Abbey",
    "lastName": "Drewett",
    "dateOfBirth": "1949-04-07",
    "startDate": "2019-10-09",
    "street": "Mendota",
    "city": "San Jose",
    "state": "California",
    "zipCode": "95123",
    "department": "Legal"
  },
  {
    "id": 36,
    "firstName": "Irwinn",
    "lastName": "Dumper",
    "dateOfBirth": "1940-12-26",
    "startDate": "2005-07-13",
    "street": "Prentice",
    "city": "New Bedford",
    "state": "Massachusetts",
    "zipCode": "02745",
    "department": "Legal"
  },
  {
    "id": 37,
    "firstName": "Lettie",
    "lastName": "Coltart",
    "dateOfBirth": "1928-12-30",
    "startDate": "2010-12-08",
    "street": "Dorton",
    "city": "Detroit",
    "state": "Michigan",
    "zipCode": "48275",
    "department": "HumanResources"
  },
  {
    "id": 38,
    "firstName": "Merrick",
    "lastName": "Pawley",
    "dateOfBirth": "1988-10-27",
    "startDate": "2021-05-28",
    "street": "Oak Valley",
    "city": "El Paso",
    "state": "Texas",
    "zipCode": "88514",
    "department": "Marketing"
  },
  {
    "id": 39,
    "firstName": "Hazel",
    "lastName": "Bakesef",
    "dateOfBirth": "1932-12-01",
    "startDate": "2019-03-20",
    "street": "Meadow Valley",
    "city": "Oklahoma City",
    "state": "Oklahoma",
    "zipCode": "73173",
    "department": "HumanResources"
  },
  {
    "id": 40,
    "firstName": "Anastassia",
    "lastName": "Ansell",
    "dateOfBirth": "1998-01-13",
    "startDate": "2010-06-23",
    "street": "Melody",
    "city": "Dallas",
    "state": "Texas",
    "zipCode": "75277",
    "department": "Marketing"
  },
  {
    "id": 41,
    "firstName": "Sheri",
    "lastName": "Chitter",
    "dateOfBirth": "1931-03-29",
    "startDate": "2000-11-07",
    "street": "Sommers",
    "city": "Jacksonville",
    "state": "Florida",
    "zipCode": "32209",
    "department": "Marketing"
  },
  {
    "id": 42,
    "firstName": "Hayley",
    "lastName": "Woodington",
    "dateOfBirth": "1998-11-06",
    "startDate": "2016-05-13",
    "street": "Donald",
    "city": "Stockton",
    "state": "California",
    "zipCode": "95205",
    "department": "Sales"
  },
  {
    "id": 43,
    "firstName": "Ellsworth",
    "lastName": "MacAlester",
    "dateOfBirth": "1927-09-09",
    "startDate": "2004-07-29",
    "street": "Miller",
    "city": "Fort Worth",
    "state": "Texas",
    "zipCode": "76147",
    "department": "Marketing"
  },
  {
    "id": 44,
    "firstName": "Fan",
    "lastName": "Gilli",
    "dateOfBirth": "1931-09-27",
    "startDate": "2013-02-16",
    "street": "Continental",
    "city": "Atlanta",
    "state": "Georgia",
    "zipCode": "31136",
    "department": "Sales"
  },
  {
    "id": 45,
    "firstName": "Wyn",
    "lastName": "Scogin",
    "dateOfBirth": "1925-08-27",
    "startDate": "2002-01-14",
    "street": "Garrison",
    "city": "Wichita",
    "state": "Kansas",
    "zipCode": "67205",
    "department": "Sales"
  },
  {
    "id": 46,
    "firstName": "Cyrillus",
    "lastName": "Burrill",
    "dateOfBirth": "1976-06-24",
    "startDate": "2005-02-25",
    "street": "Schlimgen",
    "city": "Boca Raton",
    "state": "Florida",
    "zipCode": "33487",
    "department": "HumanResources"
  },
  {
    "id": 47,
    "firstName": "Elga",
    "lastName": "Epgrave",
    "dateOfBirth": "1989-05-28",
    "startDate": "2004-07-05",
    "street": "4th",
    "city": "Arlington",
    "state": "Texas",
    "zipCode": "76016",
    "department": "Marketing"
  },
  {
    "id": 48,
    "firstName": "Willard",
    "lastName": "Muress",
    "dateOfBirth": "2004-06-10",
    "startDate": "2002-05-02",
    "street": "Ramsey",
    "city": "Mobile",
    "state": "Alabama",
    "zipCode": "36641",
    "department": "HumanResources"
  },
  {
    "id": 49,
    "firstName": "Tootsie",
    "lastName": "Rockhall",
    "dateOfBirth": "2003-09-14",
    "startDate": "2016-06-30",
    "street": "Kings",
    "city": "Torrance",
    "state": "California",
    "zipCode": "90505",
    "department": "Marketing"
  },
  {
    "id": 50,
    "firstName": "Sarita",
    "lastName": "Tapenden",
    "dateOfBirth": "1924-06-29",
    "startDate": "2018-02-11",
    "street": "New Castle",
    "city": "Beaumont",
    "state": "Texas",
    "zipCode": "77713",
    "department": "Marketing"
  },
  {
    "id": 51,
    "firstName": "Thomasina",
    "lastName": "Glencross",
    "dateOfBirth": "1960-11-15",
    "startDate": "2008-08-02",
    "street": "Mariners Cove",
    "city": "Denver",
    "state": "Colorado",
    "zipCode": "80235",
    "department": "Sales"
  },
  {
    "id": 52,
    "firstName": "Orrin",
    "lastName": "Baugham",
    "dateOfBirth": "1965-07-15",
    "startDate": "2012-03-24",
    "street": "Oakridge",
    "city": "San Antonio",
    "state": "Texas",
    "zipCode": "78220",
    "department": "Legal"
  },
  {
    "id": 53,
    "firstName": "Lonnard",
    "lastName": "Thake",
    "dateOfBirth": "1952-01-18",
    "startDate": "2006-09-12",
    "street": "Anderson",
    "city": "Boston",
    "state": "Massachusetts",
    "zipCode": "02124",
    "department": "HumanResources"
  },
  {
    "id": 54,
    "firstName": "Licha",
    "lastName": "Eamer",
    "dateOfBirth": "1953-10-30",
    "startDate": "2017-03-13",
    "street": "Westend",
    "city": "Washington",
    "state": "District of Columbia",
    "zipCode": "20420",
    "department": "HumanResources"
  },
  {
    "id": 55,
    "firstName": "Dalston",
    "lastName": "Lively",
    "dateOfBirth": "1958-03-05",
    "startDate": "2010-04-22",
    "street": "Killdeer",
    "city": "Albuquerque",
    "state": "New Mexico",
    "zipCode": "87195",
    "department": "HumanResources"
  },
  {
    "id": 56,
    "firstName": "Prue",
    "lastName": "Dubock",
    "dateOfBirth": "1933-08-23",
    "startDate": "2015-02-07",
    "street": "Holy Cross",
    "city": "Columbus",
    "state": "Georgia",
    "zipCode": "31914",
    "department": "Legal"
  },
  {
    "id": 57,
    "firstName": "Kaycee",
    "lastName": "Elsby",
    "dateOfBirth": "1973-12-18",
    "startDate": "2014-04-15",
    "street": "Duke",
    "city": "Fort Lauderdale",
    "state": "Florida",
    "zipCode": "33305",
    "department": "Marketing"
  },
  {
    "id": 58,
    "firstName": "Pattie",
    "lastName": "Breinl",
    "dateOfBirth": "1959-10-29",
    "startDate": "2003-08-01",
    "street": "Lighthouse Bay",
    "city": "Houston",
    "state": "Texas",
    "zipCode": "77060",
    "department": "HumanResources"
  },
  {
    "id": 59,
    "firstName": "Iorgo",
    "lastName": "Axston",
    "dateOfBirth": "1960-09-22",
    "startDate": "2008-02-07",
    "street": "Washington",
    "city": "Camden",
    "state": "New Jersey",
    "zipCode": "08104",
    "department": "Engineering"
  },
  {
    "id": 60,
    "firstName": "Gannie",
    "lastName": "Loreit",
    "dateOfBirth": "1975-01-19",
    "startDate": "2001-06-28",
    "street": "Fisk",
    "city": "Beaverton",
    "state": "Oregon",
    "zipCode": "97075",
    "department": "Legal"
  },
  {
    "id": 61,
    "firstName": "Aguistin",
    "lastName": "Franschini",
    "dateOfBirth": "1949-10-27",
    "startDate": "2015-12-15",
    "street": "Eagan",
    "city": "Fort Myers",
    "state": "Florida",
    "zipCode": "33913",
    "department": "Marketing"
  },
  {
    "id": 62,
    "firstName": "Neddy",
    "lastName": "Casterou",
    "dateOfBirth": "1950-03-17",
    "startDate": "2015-05-15",
    "street": "Aberg",
    "city": "Erie",
    "state": "Pennsylvania",
    "zipCode": "16510",
    "department": "Marketing"
  },
  {
    "id": 63,
    "firstName": "Laura",
    "lastName": "Arbuckel",
    "dateOfBirth": "1990-03-15",
    "startDate": "2011-09-11",
    "street": "Bashford",
    "city": "Salt Lake City",
    "state": "Utah",
    "zipCode": "84152",
    "department": "HumanResources"
  },
  {
    "id": 64,
    "firstName": "Roseann",
    "lastName": "Lockey",
    "dateOfBirth": "1974-01-19",
    "startDate": "2017-05-11",
    "street": "Jenna",
    "city": "Abilene",
    "state": "Texas",
    "zipCode": "79699",
    "department": "Marketing"
  },
  {
    "id": 65,
    "firstName": "Caesar",
    "lastName": "Jurczik",
    "dateOfBirth": "1937-08-31",
    "startDate": "2009-05-28",
    "street": "Pennsylvania",
    "city": "Fargo",
    "state": "North Dakota",
    "zipCode": "58106",
    "department": "Marketing"
  },
  {
    "id": 66,
    "firstName": "Wells",
    "lastName": "Illsley",
    "dateOfBirth": "1932-06-06",
    "startDate": "2006-12-17",
    "street": "Menomonie",
    "city": "Syracuse",
    "state": "New York",
    "zipCode": "13224",
    "department": "Engineering"
  },
  {
    "id": 67,
    "firstName": "Rustie",
    "lastName": "Dudgeon",
    "dateOfBirth": "1937-02-07",
    "startDate": "2015-05-03",
    "street": "Hoffman",
    "city": "San Francisco",
    "state": "California",
    "zipCode": "94159",
    "department": "Sales"
  },
  {
    "id": 68,
    "firstName": "Collette",
    "lastName": "Sherland",
    "dateOfBirth": "1988-05-29",
    "startDate": "2021-06-17",
    "street": "Toban",
    "city": "Fresno",
    "state": "California",
    "zipCode": "93778",
    "department": "Sales"
  },
  {
    "id": 69,
    "firstName": "Erna",
    "lastName": "Suddaby",
    "dateOfBirth": "1932-06-14",
    "startDate": "2000-10-19",
    "street": "Anderson",
    "city": "Cleveland",
    "state": "Ohio",
    "zipCode": "44118",
    "department": "Legal"
  },
  {
    "id": 70,
    "firstName": "Livvie",
    "lastName": "Werndly",
    "dateOfBirth": "1965-03-11",
    "startDate": "2021-01-13",
    "street": "Commercial",
    "city": "Lexington",
    "state": "Kentucky",
    "zipCode": "40505",
    "department": "Sales"
  },
  {
    "id": 71,
    "firstName": "Atlanta",
    "lastName": "Ferrarello",
    "dateOfBirth": "1975-08-12",
    "startDate": "2001-06-19",
    "street": "Linden",
    "city": "Kansas City",
    "state": "Kansas",
    "zipCode": "66105",
    "department": "Marketing"
  },
  {
    "id": 72,
    "firstName": "Kissie",
    "lastName": "Santorini",
    "dateOfBirth": "1969-03-22",
    "startDate": "2003-10-28",
    "street": "Fulton",
    "city": "Austin",
    "state": "Texas",
    "zipCode": "78783",
    "department": "Sales"
  },
  {
    "id": 73,
    "firstName": "Jillana",
    "lastName": "MacAllaster",
    "dateOfBirth": "1987-07-07",
    "startDate": "2004-04-26",
    "street": "Weeping Birch",
    "city": "Charlotte",
    "state": "North Carolina",
    "zipCode": "28299",
    "department": "Legal"
  },
  {
    "id": 74,
    "firstName": "Melva",
    "lastName": "Coatsworth",
    "dateOfBirth": "1978-09-15",
    "startDate": "2012-01-12",
    "street": "Bellgrove",
    "city": "Nashville",
    "state": "Tennessee",
    "zipCode": "37240",
    "department": "Engineering"
  },
  {
    "id": 75,
    "firstName": "Ladonna",
    "lastName": "Jorck",
    "dateOfBirth": "2003-01-21",
    "startDate": "2010-02-01",
    "street": "Towne",
    "city": "Naples",
    "state": "Florida",
    "zipCode": "34114",
    "department": "Engineering"
  },
  {
    "id": 76,
    "firstName": "Perla",
    "lastName": "Ewdale",
    "dateOfBirth": "1966-11-11",
    "startDate": "2004-04-06",
    "street": "Barby",
    "city": "Pittsburgh",
    "state": "Pennsylvania",
    "zipCode": "15220",
    "department": "Legal"
  },
  {
    "id": 77,
    "firstName": "Tony",
    "lastName": "MacInnes",
    "dateOfBirth": "1975-09-30",
    "startDate": "2017-02-09",
    "street": "Gale",
    "city": "San Antonio",
    "state": "Texas",
    "zipCode": "78296",
    "department": "Sales"
  },
  {
    "id": 78,
    "firstName": "Trevor",
    "lastName": "Glendza",
    "dateOfBirth": "1958-06-20",
    "startDate": "2006-03-19",
    "street": "Lunder",
    "city": "El Paso",
    "state": "Texas",
    "zipCode": "79911",
    "department": "Sales"
  },
  {
    "id": 79,
    "firstName": "Marwin",
    "lastName": "Sains",
    "dateOfBirth": "1995-03-17",
    "startDate": "2005-10-12",
    "street": "Buell",
    "city": "Worcester",
    "state": "Massachusetts",
    "zipCode": "01654",
    "department": "Legal"
  },
  {
    "id": 80,
    "firstName": "Lisabeth",
    "lastName": "Astling",
    "dateOfBirth": "1933-03-18",
    "startDate": "2020-05-15",
    "street": "Summerview",
    "city": "Bloomington",
    "state": "Indiana",
    "zipCode": "47405",
    "department": "Engineering"
  },
  {
    "id": 81,
    "firstName": "Petronia",
    "lastName": "Warbeys",
    "dateOfBirth": "1947-04-20",
    "startDate": "2019-12-17",
    "street": "Barby",
    "city": "Albany",
    "state": "New York",
    "zipCode": "12237",
    "department": "Legal"
  },
  {
    "id": 82,
    "firstName": "Bel",
    "lastName": "Wenzel",
    "dateOfBirth": "1979-03-16",
    "startDate": "2012-03-26",
    "street": "Florence",
    "city": "Riverside",
    "state": "California",
    "zipCode": "92513",
    "department": "Legal"
  },
  {
    "id": 83,
    "firstName": "Francis",
    "lastName": "Dorant",
    "dateOfBirth": "1942-09-18",
    "startDate": "2016-09-24",
    "street": "Di Loreto",
    "city": "Aurora",
    "state": "Colorado",
    "zipCode": "80045",
    "department": "Sales"
  },
  {
    "id": 84,
    "firstName": "Ambrosi",
    "lastName": "Alenov",
    "dateOfBirth": "1982-05-22",
    "startDate": "2010-07-22",
    "street": "Toban",
    "city": "Stockton",
    "state": "California",
    "zipCode": "95205",
    "department": "Sales"
  },
  {
    "id": 85,
    "firstName": "Marjorie",
    "lastName": "Gallaway",
    "dateOfBirth": "1926-01-15",
    "startDate": "2019-10-02",
    "street": "Spohn",
    "city": "Austin",
    "state": "Texas",
    "zipCode": "78703",
    "department": "Legal"
  },
  {
    "id": 86,
    "firstName": "Erinn",
    "lastName": "Stonuary",
    "dateOfBirth": "1997-08-29",
    "startDate": "2018-11-04",
    "street": "Southridge",
    "city": "Madison",
    "state": "Wisconsin",
    "zipCode": "53716",
    "department": "Legal"
  },
  {
    "id": 87,
    "firstName": "Joice",
    "lastName": "Dennett",
    "dateOfBirth": "1950-06-30",
    "startDate": "2001-04-13",
    "street": "Melrose",
    "city": "Chula Vista",
    "state": "California",
    "zipCode": "91913",
    "department": "HumanResources"
  },
  {
    "id": 88,
    "firstName": "Vanessa",
    "lastName": "Krolak",
    "dateOfBirth": "1928-02-14",
    "startDate": "2021-09-18",
    "street": "Darwin",
    "city": "San Antonio",
    "state": "Texas",
    "zipCode": "78205",
    "department": "HumanResources"
  },
  {
    "id": 89,
    "firstName": "Tisha",
    "lastName": "Ogers",
    "dateOfBirth": "1987-08-16",
    "startDate": "2002-06-25",
    "street": "Namekagon",
    "city": "Albany",
    "state": "New York",
    "zipCode": "12227",
    "department": "HumanResources"
  },
  {
    "id": 90,
    "firstName": "Lucais",
    "lastName": "Pusill",
    "dateOfBirth": "1951-12-26",
    "startDate": "2020-11-07",
    "street": "Forest Dale",
    "city": "Pittsburgh",
    "state": "Pennsylvania",
    "zipCode": "15250",
    "department": "Legal"
  },
  {
    "id": 91,
    "firstName": "Edythe",
    "lastName": "Soro",
    "dateOfBirth": "1930-02-16",
    "startDate": "2018-10-18",
    "street": "Drewry",
    "city": "Worcester",
    "state": "Massachusetts",
    "zipCode": "01605",
    "department": "Engineering"
  },
  {
    "id": 92,
    "firstName": "Bird",
    "lastName": "Carson",
    "dateOfBirth": "1984-08-08",
    "startDate": "2002-05-04",
    "street": "Cherokee",
    "city": "Rochester",
    "state": "Minnesota",
    "zipCode": "55905",
    "department": "Sales"
  },
  {
    "id": 93,
    "firstName": "Jen",
    "lastName": "Atkyns",
    "dateOfBirth": "1987-05-27",
    "startDate": "2017-02-20",
    "street": "Dunning",
    "city": "London",
    "state": "Kentucky",
    "zipCode": "40745",
    "department": "Engineering"
  },
  {
    "id": 94,
    "firstName": "Malachi",
    "lastName": "Songest",
    "dateOfBirth": "1951-12-01",
    "startDate": "2015-04-07",
    "street": "Gateway",
    "city": "Chicago",
    "state": "Illinois",
    "zipCode": "60630",
    "department": "Sales"
  },
  {
    "id": 95,
    "firstName": "Ronnie",
    "lastName": "Sunley",
    "dateOfBirth": "1939-10-25",
    "startDate": "2003-03-24",
    "street": "Hermina",
    "city": "Chicago",
    "state": "Illinois",
    "zipCode": "60636",
    "department": "Engineering"
  },
  {
    "id": 96,
    "firstName": "Demeter",
    "lastName": "Cornier",
    "dateOfBirth": "1994-01-01",
    "startDate": "2007-03-26",
    "street": "Birchwood",
    "city": "Newton",
    "state": "Massachusetts",
    "zipCode": "02458",
    "department": "Sales"
  },
  {
    "id": 97,
    "firstName": "Orelie",
    "lastName": "Belfield",
    "dateOfBirth": "1934-07-06",
    "startDate": "2017-12-28",
    "street": "Barby",
    "city": "Washington",
    "state": "District of Columbia",
    "zipCode": "20220",
    "department": "Engineering"
  },
  {
    "id": 98,
    "firstName": "Deni",
    "lastName": "Breakspear",
    "dateOfBirth": "2002-03-06",
    "startDate": "2018-10-17",
    "street": "Toban",
    "city": "Memphis",
    "state": "Tennessee",
    "zipCode": "38161",
    "department": "Legal"
  },
  {
    "id": 99,
    "firstName": "Fiann",
    "lastName": "Ketchell",
    "dateOfBirth": "1968-01-28",
    "startDate": "2004-01-31",
    "street": "Mosinee",
    "city": "Lubbock",
    "state": "Texas",
    "zipCode": "79405",
    "department": "Legal"
  },
  {
    "id": 100,
    "firstName": "Palm",
    "lastName": "Gillham",
    "dateOfBirth": "1934-07-10",
    "startDate": "2017-11-05",
    "street": "Ramsey",
    "city": "Alhambra",
    "state": "California",
    "zipCode": "91841",
    "department": "Marketing"
  }
]

module.exports = data;